apiVersion: apps/v1
kind: Deployment
metadata:
  name: service.bbb
  labels:
    app: service.bbb
spec:
  hostNetwork: true
  selector:
    matchLabels:
      app: service.bbb
  template:
    metadata:
      labels:
        app: service.bbb
    spec:
      containers:
        - name: service.bbb
          image: service.bbb-image
          command:
            #- /bin/sh
            #- -c
            #- sleep infinity
            - /build/service.bbb_main
            #- -db_uri=consumer:@tcp(mysql-server:3306)/consumer_db?parseTime=true
            #- -producer_grpc_address=producer-api:1234
          ports:
            - containerPort: 1234

